-- return {
--   {
--     "MeanderingProgrammer/render-markdown.nvim",
--     dependencies = { "nvim-treesitter/nvim-treesitter" },
--     ft = { "markdown" },
--     opts = {
--       render_modes = { "n", "c" },
--     },
--   },
-- }
